[build]
  command = "npm run build"
  publish = "build"

# Optional: enable caching of node modules for faster builds
[build.environment]
  NPM_FLAGS = "--no-fund"

# Optional: SPA fallback so client-side routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
